# Generated by Django 5.1.4 on 2025-12-12 21:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('statut_juridique', models.CharField(max_length=100)),
                ('date_creation', models.DateField()),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique de la fonctionnalité (ex: MOBILE_MONEY, SMS_NOTIFICATIONS)', max_length=50, unique=True)),
                ('nom', models.CharField(help_text='Nom de la fonctionnalité', max_length=100)),
                ('description', models.TextField(help_text='Description détaillée de la fonctionnalité')),
                ('icone', models.CharField(blank=True, help_text="Classe CSS de l'icône (ex: fa-mobile, fa-bell)", max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Fonctionnalité active sur la plateforme')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MethodePaiementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('OM', 'Orange Money')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementStatutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('ECHOUE', 'Échoué')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(help_text='Numéro de téléphone pour Mobile Money et notifications SMS', max_length=20, unique=True)),
                ('photo_profil', models.ImageField(blank=True, help_text='Photo de profil du membre', null=True, upload_to='profils/')),
                ('adresse', models.TextField(blank=True, help_text='Adresse physique')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('A_JOUR', 'À jour'), ('EN_RETARD', 'En retard'), ('SUSPENDU', 'Suspendu')], default='A_JOUR', help_text='Statut par rapport aux cotisations', max_length=20)),
                ('notification_sms', models.BooleanField(default=True, help_text='Recevoir les notifications par SMS')),
                ('notification_email', models.BooleanField(default=True, help_text='Recevoir les notifications par email')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_inscription'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('type_cotisation', models.CharField(max_length=50)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='mboa_assoc_app.association')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='mboa_assoc_app.cotisation')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('methode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='mboa_assoc_app.methodepaiementmodel')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='mboa_assoc_app.paiementstatutmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_commission', models.DateField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='mboa_assoc_app.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='PlanFonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_utilisation', models.IntegerField(blank=True, help_text="Limite d'utilisation (ex: 100 SMS/mois, null = illimité)", null=True)),
                ('parametres', models.JSONField(blank=True, default=dict, help_text='Paramètres additionnels spécifiques (JSON)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fonctionnalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_fonctionnalites', to='mboa_assoc_app.fonctionnalite')),
            ],
            options={
                'verbose_name': 'Plan-Fonctionnalité',
                'verbose_name_plural': 'Plans-Fonctionnalités',
                'ordering': ['plan', 'fonctionnalite'],
            },
        ),
        migrations.CreateModel(
            name='PlanTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_plan', models.CharField(choices=[('PRO', 'Pro'), ('ENTREPRISE', 'Entreprise')], help_text='Type de plan tarifaire', max_length=20)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('limite_membres', models.IntegerField()),
                ('actif', models.BooleanField(default=True, help_text='Plan disponible à la souscription')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fonctionnalites', models.ManyToManyField(help_text='Fonctionnalités incluses dans ce plan', related_name='plans', through='mboa_assoc_app.PlanFonctionnalite', to='mboa_assoc_app.fonctionnalite')),
            ],
            options={
                'verbose_name': 'Plan Tarifaire',
                'verbose_name_plural': 'Plans Tarifaires',
                'ordering': ['prix_mensuel'],
            },
        ),
        migrations.AddField(
            model_name='planfonctionnalite',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_fonctionnalites', to='mboa_assoc_app.plantarifaire'),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], max_length=20)),
                ('auto_renouvellement', models.BooleanField(default=False, help_text="Renouvellement automatique de l'abonnement")),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='mboa_assoc_app.association')),
                ('plan', models.ForeignKey(help_text='Plan tarifaire souscrit', on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='mboa_assoc_app.plantarifaire')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(choices=[('TRESORIER', 'Trésorier'), ('ADMIN', 'Administrateur'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=20)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to=settings.AUTH_USER_MODEL)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesions', to='mboa_assoc_app.association')),
            ],
            options={
                'unique_together': {('membre', 'association')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('RAPPEL_COTISATION', 'Rappel de cotisation'), ('PAIEMENT_RECU', 'Paiement reçu'), ('PAIEMENT_ECHOUE', 'Paiement échoué'), ('NOUVEAU_MEMBRE', 'Nouveau membre'), ('RETARD_PAIEMENT', 'Retard de paiement'), ('INFO_GENERALE', 'Information générale')], help_text='Type de notification', max_length=30)),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Contenu du message')),
                ('envoye_sms', models.BooleanField(default=False)),
                ('envoye_email', models.BooleanField(default=False)),
                ('lu', models.BooleanField(default=False, help_text='Notification lue par le membre')),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('membre', models.ForeignKey(help_text='Destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['membre', '-date_creation'], name='mboa_assoc__membre__cc43de_idx'), models.Index(fields=['lu', 'membre'], name='mboa_assoc__lu_a58f12_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='planfonctionnalite',
            unique_together={('plan', 'fonctionnalite')},
        ),
    ]
