# Generated by Django 5.1.4 on 2025-12-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mboa_assoc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
