# Generated by Django 5.1.4 on 2025-12-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mboa_assoc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='date_verification_telephone',
            field=models.DateTimeField(blank=True, help_text='Date de vérification du téléphone', null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='quartier',
            field=models.CharField(blank=True, help_text='Quartier de résidence', max_length=100),
        ),
        migrations.AddField(
            model_name='membre',
            name='telephone_verifie',
            field=models.BooleanField(default=False, help_text='Indique si le numéro de téléphone a été vérifié par OTP'),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='role',
            field=models.CharField(choices=[('TRESORIER', 'Trésorier'), ('ADMIN', 'Administrateur'), ('MEMBRE', 'Membre'), ('PRESIDENT', 'Président')], default='MEMBRE', max_length=20),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Numéro de téléphone au format +237XXXXXXXXX', max_length=20)),
                ('code', models.CharField(help_text='Code OTP à 6 chiffres', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création du code')),
                ('expires_at', models.DateTimeField(help_text="Date et heure d'expiration du code (10 minutes après création)")),
                ('is_validated', models.BooleanField(default=False, help_text='Indique si le code a été validé avec succès')),
                ('is_expired', models.BooleanField(default=False, help_text='Indique si le code a expiré ou été invalidé')),
                ('attempts', models.IntegerField(default=0, help_text='Nombre de tentatives de validation')),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date et heure d'envoi du SMS", null=True)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telephone', '-created_at'], name='mboa_assoc__telepho_aa4f7f_idx'), models.Index(fields=['expires_at'], name='mboa_assoc__expires_be2e77_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Numéro de téléphone bloqué', max_length=20, unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure du blocage')),
                ('blocked_until', models.DateTimeField(help_text='Date et heure de fin du blocage')),
                ('total_failures', models.IntegerField(default=0, help_text="Nombre total d'échecs ayant conduit au blocage")),
                ('reason', models.CharField(help_text='Raison du blocage', max_length=100)),
            ],
            options={
                'verbose_name': 'Blocage de téléphone',
                'verbose_name_plural': 'Blocages de téléphone',
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['telephone'], name='mboa_assoc__telepho_c8f018_idx'), models.Index(fields=['blocked_until'], name='mboa_assoc__blocked_68a92e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la tentative')),
                ('success', models.BooleanField(help_text='Indique si la tentative a réussi')),
                ('ip_address', models.GenericIPAddressField(help_text="Adresse IP de l'utilisateur")),
                ('otp_code', models.ForeignKey(help_text='Code OTP concerné', on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='mboa_assoc_app.otpcode')),
            ],
            options={
                'verbose_name': 'Tentative OTP',
                'verbose_name_plural': 'Tentatives OTP',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['otp_code', '-attempted_at'], name='mboa_assoc__otp_cod_a8c1fb_idx')],
            },
        ),
    ]
