# Generated by Django 5.1.4 on 2025-12-15 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mboa_assoc_app', '0002_membre_date_verification_telephone_membre_quartier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Code unique d'invitation", max_length=50, unique=True)),
                ('telephone_invite', models.CharField(help_text='Numéro de téléphone invité', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(help_text="Date d'expiration de l'invitation (7 jours)")),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='mboa_assoc_app.association')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['code'], name='mboa_assoc__code_02a5f7_idx'), models.Index(fields=['telephone_invite', 'statut'], name='mboa_assoc__telepho_fb83fa_idx')],
            },
        ),
    ]
